steps:
 - id: Maven Build
   name: maven:3-jdk-8
   entrypoint: mvn
   args: ['clean','package']
 - id: Docker Build and Tag
   name: gcr.io/cloud-builders/docker
   args: ['build', '-t', 'eu.gcr.io/calm-catfish-307320/spring-boot:$SHORT_SHA', '.']
 - id: Docker Push
   name: gcr.io/cloud-builders/docker
   args: ['push', 'eu.gcr.io/calm-catfish-307320/spring-boot:$SHORT_SHA']
 - id: Helm Install Springboot Chart
   name: gcr.io/$PROJECT_ID/helm
   args: ["upgrade", "-i", "-f", "values.yaml", "spring-boot", "helm-charts-templates/helm-chart-sample", "--set", "image.tag=$SHORT_SHA"]
   env:
     - TILLERLESS=true
     - CLOUDSDK_COMPUTE_ZONE=us-west2-b
     - CLOUDSDK_CONTAINER_CLUSTER=calm-catfish-307320
     - HELM_REPO_URL=gs://helm-charts-templates
     - HELM_REPO_NAME=helm-charts-templates
     - GCS_PLUGIN_VERSION=0.3.9
